### ISSUE TITLE
Run code without live-reload

### ISSUE THREAD

**Issue by criskell** [maykbrito/fronteditorv2#12]
Hi, very good project, congratulations.
I wanted to know if there is any way to run the HTML, CSS and JS code without using live-reload.
For example, clicking on some button, pressing some shortcut (example: ctrl + enter) and so on.
Thanks.

**Comment by diego3g** [comment]
@criskell You have the option to disable live reload on the preview header.
![image](https://user-images.githubusercontent.com/2254731/173232573-ecc36912-cbec-4a66-a8c4-07dc2eca02a8.png)
Then, you can use CTRL + S (CMD + S on Mac) to save the file and reload the preview.

**Comment by criskell** [comment]
Great thank you
