### ISSUE TITLE
Que show esse projeto!! to preparando os papeis para adoção já Maykão

### ISSUE THREAD

**Issue by devjosecarlosteles** [maykbrito/fronteditorv2#7]

**Comment by diego3g** [comment]
@devjosecarlosteles tu usa `else`?

**Comment by devjosecarlosteles** [comment]
else ? como assim sksk

**Comment by maykbrito** [comment]
https://www.twitch.tv/videos/1310427685

**Comment by devjosecarlosteles** [comment]
@maykbrito  skskksk a não, o cara simplesmente se negou a usar o else "eu faço meu javascript"' skskk amo vocês demais
